"use client";

import { FormEvent, useRef, useState } from "react";
import { BlogHeader } from "@/components/BlogHeader";

type SubmissionState = "idle" | "sending" | "success" | "error";
const createHumanCheck = () => { const first = Math.floor(Math.random() * 8) + 2; const second = Math.floor(Math.random() * 8) + 1; return { first, second, answer: first + second }; };

export default function ContactPage() {
  const [submission, setSubmission] = useState<SubmissionState>("idle"); const [message, setMessage] = useState(""); const [humanCheck, setHumanCheck] = useState(createHumanCheck); const [humanAnswer, setHumanAnswer] = useState(""); const editor = useRef<HTMLDivElement>(null);
  function format(command: "bold" | "italic" | "insertUnorderedList" | "formatBlock") { editor.current?.focus(); document.execCommand(command, false, command === "formatBlock" ? "blockquote" : undefined); setMessage(editor.current?.innerHTML || ""); }
  function addLink() { const url = window.prompt("Enter the link URL"); if (!url) return; editor.current?.focus(); document.execCommand("createLink", false, url); setMessage(editor.current?.innerHTML || ""); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editor.current?.innerText.trim() || Number(humanAnswer) !== humanCheck.answer) { setSubmission("error"); return; } setSubmission("sending"); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...Object.fromEntries(form), message }) }); if (!response.ok) throw new Error(); event.currentTarget.reset(); editor.current.innerHTML = ""; setMessage(""); setHumanAnswer(""); setHumanCheck(createHumanCheck()); setSubmission("success"); } catch { setSubmission("error"); } }
  return <><BlogHeader /><main className="content-page"><p className="section-label">GET IN TOUCH</p><h1>Contact</h1><p className="page-intro">Have a question or want to collaborate? Send a message.</p>{submission === "success" ? <section className="contact-success" role="status"><span aria-hidden="true">✓</span><div><h2>Message sent</h2><p>Thank you for reaching out. Your message has been received and we’ll get back to you soon.</p><button type="button" onClick={() => setSubmission("idle")}>Send another message</button></div></section> : <form className="contact-form rich-contact" onSubmit={submit}><input name="name" placeholder="Your name" required /><input name="email" type="email" placeholder="Your email" required /><label className="human-check">Human check: what is {humanCheck.first} + {humanCheck.second}?<input value={humanAnswer} onChange={(event) => setHumanAnswer(event.target.value)} inputMode="numeric" placeholder="Your answer" required /></label><div className="rich-editor"><div className="composer-toolbar" role="toolbar" aria-label="Message formatting"><button type="button" onClick={() => format("bold")} aria-label="Bold"><b>B</b></button><button type="button" onClick={() => format("italic")} aria-label="Italic"><i>I</i></button><button type="button" onClick={() => format("insertUnorderedList")} aria-label="Bulleted list">•</button><button type="button" onClick={() => format("formatBlock")} aria-label="Quote">❝</button><button type="button" onClick={addLink} aria-label="Add link">↗</button><span>{(editor.current?.innerText || "").length}/6000</span></div><div ref={editor} className="contact-editor" contentEditable suppressContentEditableWarning role="textbox" aria-multiline="true" aria-label="Your message" data-placeholder="Write your message…" onInput={(event) => setMessage(event.currentTarget.innerHTML)} /></div>{submission === "error" && <small className="contact-error" role="alert">Please enter a message and answer the human check correctly.</small>}<button disabled={submission === "sending"}>{submission === "sending" ? "Sending…" : "Send message"}</button></form>}</main></>;
}
