"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { LanguageSelect, type Locale } from "@/components/LanguageSelect";
const labels: Record<Locale, { nav: string[]; view: string; signOut: string; menu: string }> = { en: { nav: ["Overview", "Posts", "Projects", "Pages", "Comments", "Analytics", "Profile", "Settings"], view: "View site ↗", signOut: "Sign out", menu: "Open admin menu" }, fr: { nav: ["Vue d’ensemble", "Articles", "Projets", "Pages", "Commentaires", "Analyses", "Profil", "Réglages"], view: "Voir le site ↗", signOut: "Déconnexion", menu: "Ouvrir le menu" }, ar: { nav: ["نظرة عامة", "المقالات", "المشاريع", "الصفحات", "التعليقات", "التحليلات", "الملف الشخصي", "الإعدادات"], view: "عرض الموقع ↗", signOut: "تسجيل الخروج", menu: "فتح القائمة" } };
const paths = ["/admin", "/admin/posts", "/admin/projects", "/admin/pages", "/admin/comments", "/admin/analytics", "/admin/profile", "/admin/settings"];
export function AdminShell({ children }: { children: React.ReactNode }) { const pathname = usePathname(); const router = useRouter(); const [locale, setLocale] = useState<Locale>("en"); const [open, setOpen] = useState(false); useEffect(() => { const saved = localStorage.getItem("poilian-locale"); if (saved === "en" || saved === "fr" || saved === "ar") setLocale(saved); }, []); async function logout() { await fetch("/api/admin/logout", { method: "POST" }); router.replace("/admin"); router.refresh(); } const text = labels[locale]; return <div className="poilian-admin" dir={locale === "ar" ? "rtl" : "ltr"}><header className="poilian-admin-header"><div className="admin-header-row"><Link href="/admin" className="poilian-admin-logo"><Image src="/brand.png" alt="Poilian" width={125} height={52} priority /></Link><div className="admin-header-tools"><LanguageSelect value={locale} onLocaleChange={setLocale} /><Link href="/en">{text.view}</Link><button className="admin-menu-toggle" onClick={() => setOpen((value) => !value)} aria-label={text.menu} aria-expanded={open}><i /><i /><i /></button></div></div><nav className={open ? "is-open" : ""} aria-label="Admin dashboard">{paths.map((href, index) => <Link key={href} href={href} onClick={() => setOpen(false)} className={pathname === href ? "active" : ""}>{text.nav[index]}</Link>)}<button className="admin-mobile-signout" onClick={logout}>{text.signOut}</button></nav><button className="admin-desktop-signout" onClick={logout}>{text.signOut}</button></header><main className="poilian-admin-main">{children}</main><footer className="admin-footer"><span>Copyright © 1999 - 2026 Poilian. All Rights Reserved.</span><nav aria-label="Admin legal links"><Link href="/privacy">Privacy Policy</Link><Link href="/privacy">Do not sell my personal information</Link></nav></footer></div>; }
