"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { SiteLogo } from "@/components/SiteLogo";

export function AdminLogin() {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [showPassword, setShowPassword] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.get("email"), password: form.get("password") }) }); const result = await response.json(); if (response.ok) window.location.assign("/admin"); else { setError(result.error ?? "Unable to sign in."); setBusy(false); } }
  return <main className="admin-login robot-login"><section className="robot-login-card"><header><Link href="/en" aria-label="Poilian home"><SiteLogo alt="Poilian" width={148} height={61} priority /></Link><span>ADMIN ACCESS</span></header><div className="robot-login-layout"><div className="robot-login-copy"><p className="section-label">SECURE ACCESS</p><h1>Welcome back.</h1><p>Sign in to manage your stories, pages, projects, and site settings.</p><form onSubmit={submit}><label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></label><label>Password<div className="password-field"><input name="password" type={showPassword ? "text" : "password"} autoComplete="current-password" required placeholder="Your password" /><button type="button" onClick={() => setShowPassword((value) => !value)}>{showPassword ? "Hide" : "Show"}</button></div></label>{error && <small role="alert">{error}</small>}<button className="login-submit" disabled={busy}>{busy ? "Signing in…" : "Enter dashboard"}<span>→</span></button></form></div><aside className="robot-login-art" aria-hidden="true"><p>ACCESS<br />GRANTED</p><svg viewBox="0 0 250 250"><g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round"><rect x="74" y="38" width="102" height="73" rx="12" strokeWidth="3"/><path d="M99 38V24h52v14M91 64h22m25 0h22M110 88c10 8 22 8 32 0M87 119h76v76a28 28 0 0 1-28 28h-20a28 28 0 0 1-28-28Z" strokeWidth="3"/><circle cx="105" cy="67" r="4" fill="currentColor"/><circle cx="145" cy="67" r="4" fill="currentColor"/><path d="M102 137h46v36h-46zM112 148h10m10 0h8M87 137c-21 2-32 16-35 36m112-36c21 2 32 16 35 36M98 205l-23 25m35-25 16 25m29-25 21 25m-8-25-16 25M62 231h55m74 0h-56M54 179l-17 8 8 16m151-24 17 8-8 16" strokeWidth="3"/><path d="M187 38l20 9-7 15-20-9zM203 52l13-4" strokeWidth="2"/></g></svg><span>• • •</span></aside></div><footer><span>Protected Poilian administration</span><Link href="/en">Return to site</Link></footer></section></main>;
}
